# Generated by Django 5.1 on 2024-09-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
