# Generated by Django 5.1 on 2024-09-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRM', '0003_alter_credentials_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
