# Generated by Django 5.1 on 2024-09-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRM', '0004_alter_credentials_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORG_NAME', models.CharField(max_length=150)),
                ('CHANNEL', models.CharField(max_length=150)),
                ('TXN_ID', models.CharField(max_length=150)),
                ('CASE_ID', models.CharField(max_length=150)),
                ('PROCESSING_CODE', models.CharField(max_length=150)),
                ('DATETIME_LOCAL_TXN', models.DateTimeField(max_length=150)),
                ('DATELOGGED', models.DateTimeField(max_length=150)),
                ('TXN_AMOUNT', models.PositiveIntegerField(max_length=150)),
                ('SETTLEMENT_AMOUNT', models.PositiveIntegerField(max_length=150)),
                ('REVERSAL_STATUS', models.BooleanField()),
                ('TXN_ACTION_CODE', models.CharField(max_length=150)),
                ('MTI', models.CharField(max_length=150)),
                ('RULE_SCORE', models.IntegerField(max_length=150)),
                ('MODEL_SCORE', models.IntegerField(max_length=150)),
                ('MERCH_CAT', models.IntegerField(max_length=150)),
                ('POS_ENTRY_MODE', models.IntegerField(max_length=150)),
                ('ACCEPTOR_NAME', models.CharField(max_length=150)),
                ('ACCEPTOR_CITY', models.CharField(max_length=150)),
                ('ACCEPTOR_STATE', models.CharField(max_length=150)),
                ('ACCEPTOR_COUNTRY', models.CharField(max_length=150)),
                ('ACQ_COUNTRY', models.IntegerField(max_length=150)),
                ('ACCEPTOR_TERMID', models.CharField(max_length=150)),
                ('ACQ_BIN', models.IntegerField(max_length=150)),
                ('RRN', models.IntegerField(max_length=150)),
                ('ACCEPTOR_ID', models.CharField(max_length=150)),
                ('STAN', models.CharField(max_length=150)),
                ('CARDNUMBER', models.CharField(max_length=150)),
                ('TXN_SUB_CODE', models.CharField(max_length=150)),
                ('PRODUCT_INDICATOR', models.CharField(max_length=150)),
                ('DEPOSIT_ID', models.CharField(max_length=150)),
                ('MATCHED_RULE', models.CharField(max_length=150)),
                ('TOTAL_TXN_AMOUNT', models.IntegerField(max_length=150)),
                ('last_4_digits', models.IntegerField(max_length=150)),
            ],
            options={
                'db_table': 'FraudTransactions',
            },
        ),
    ]
