# Generated by Django 5.0.9 on 2024-09-13 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FRM', '0006_alter_fraudtransactions_acq_bin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FraudTransactions',
        ),
    ]
