# Generated by Django 5.0.9 on 2024-09-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRM', '0007_delete_fraudtransactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255)),
                ('channel', models.CharField(max_length=255)),
                ('txn_id', models.CharField(max_length=255, unique=True)),
                ('case_id', models.CharField(max_length=255)),
                ('processing_code', models.CharField(max_length=255)),
                ('datetime_local_txn', models.DateTimeField()),
                ('datelogged', models.DateField()),
                ('txn_amount', models.FloatField()),
                ('settlement_amount', models.FloatField(blank=True, null=True)),
                ('reversal_status', models.BooleanField()),
                ('txn_action_code', models.CharField(max_length=255)),
                ('mti', models.IntegerField()),
                ('rule_score', models.IntegerField()),
                ('model_score', models.IntegerField()),
                ('merch_cat', models.IntegerField()),
                ('pos_entry_mode', models.IntegerField()),
                ('acceptor_name', models.CharField(max_length=255)),
                ('acceptor_city', models.CharField(max_length=255)),
                ('acceptor_state', models.CharField(max_length=255)),
                ('acceptor_country', models.CharField(max_length=255)),
                ('acq_country', models.IntegerField()),
                ('acceptor_termid', models.CharField(max_length=255)),
                ('acq_bin', models.IntegerField()),
                ('rrn', models.IntegerField()),
                ('acceptor_id', models.CharField(max_length=255)),
                ('stan', models.CharField(max_length=255)),
                ('cardnumber', models.CharField(max_length=255)),
                ('txn_sub_code', models.FloatField(blank=True, null=True)),
                ('product_indicator', models.FloatField(blank=True, null=True)),
                ('deposit_id', models.FloatField(blank=True, null=True)),
                ('matched_rule', models.CharField(max_length=255)),
                ('total_txn_amount', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
