# Generated by Django 5.0.9 on 2024-09-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FRM', '0008_transaction'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='Transaction',
        ),
    ]
