# Generated by Django 5.0.9 on 2024-09-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRM', '0009_alter_transaction_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='datetime_local_txn',
            field=models.DateField(),
        ),
    ]
