# Generated by Django 5.0.9 on 2024-09-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRM', '0011_alter_transaction_deposit_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='rrn',
            field=models.BigIntegerField(),
        ),
    ]
