# Generated by Django 5.0.9 on 2024-09-25 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FRM', '0014_rule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
