# Generated by Django 5.0.9 on 2024-09-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRM', '0016_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='suspicious_transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=50)),
                ('channel', models.CharField(max_length=100)),
                ('txn_id', models.CharField(max_length=255, null=True, unique=True)),
                ('case_id', models.CharField(max_length=255)),
                ('processing_code', models.CharField(max_length=255)),
                ('date_time_local_txn', models.DateTimeField()),
                ('date_logged', models.DateTimeField()),
                ('txn_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('settlement_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reversal_status', models.CharField(max_length=255)),
                ('txn_action_code', models.CharField(max_length=255)),
                ('mti', models.CharField(max_length=255)),
                ('rule_score', models.CharField(max_length=255)),
                ('model_score', models.CharField(max_length=255)),
                ('merch_cat', models.CharField(max_length=255)),
                ('pos_entry_mode', models.CharField(max_length=255)),
                ('acceptor_name', models.CharField(max_length=255)),
                ('acceptor_city', models.CharField(max_length=255)),
                ('acceptor_state', models.CharField(max_length=255)),
                ('acceptor_country', models.CharField(max_length=255)),
                ('acq_country', models.CharField(max_length=255)),
                ('acceptor_termid', models.CharField(max_length=255)),
                ('acq_bin', models.CharField(max_length=255)),
                ('rrn', models.CharField(max_length=255)),
                ('acceptor_id', models.CharField(max_length=255)),
                ('stan', models.CharField(max_length=255)),
                ('cardnumber', models.CharField(max_length=255)),
                ('txn_sub_code', models.CharField(max_length=255)),
                ('product_indicator', models.CharField(max_length=255)),
                ('deposit_id', models.CharField(max_length=255)),
                ('matched_rule', models.CharField(max_length=255)),
                ('rule_id', models.BigIntegerField()),
                ('rule_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'suspicious_transaction',
            },
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
