# Generated by Django 5.0.9 on 2024-09-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRM', '0017_suspicious_transaction_delete_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspicious_transaction',
            name='txn_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
